name: Trigger auto deployment for codifytest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/codifytest-AutoDeployTrigger-2f9400fd-b17d-4626-ba0b-4acd672f0dc7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: emarrerocontainer.azurecr.io
          username: ${{ secrets.CODIFYTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.CODIFYTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: emarrerocontainer.azurecr.io/codifytest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CODIFYTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n codifytest -g DevOps --server emarrerocontainer.azurecr.io --username  ${{ secrets.CODIFYTEST_REGISTRY_USERNAME }} --password ${{ secrets.CODIFYTEST_REGISTRY_PASSWORD }}
            az containerapp update -n codifytest -g DevOps --image emarrerocontainer.azurecr.io/codifytest:${{ github.sha }}
